version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/" # Location of Dockerfile
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directory: "/" # Location of docker-compose.yml
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflows
    schedule:
      interval: "weekly"
